# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Django settings for Thoth project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import logging
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
from django.db.backends.signals import connection_created
from django.dispatch import receiver

@receiver(connection_created)
def setup_search_path(sender, connection, **kwargs):
    if connection.vendor == 'postgresql':
        db_schema = os.environ.get("DB_SCHEMA", "thoth_schema")
        with connection.cursor() as cursor:
            # Force search_path to the specific schema to ensure isolation
            # We don't include 'public' here during migration setup to avoid introspection conflicts
            cursor.execute(f"SET search_path TO {db_schema}")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Explicitly load .env.docker from the project root to ensure correct settings.
# This overrides any variables set by the shell, making it reliable for both
# local and Docker environments.
import sys

# Load environment configuration
# Priority: .env.local (local dev) > .env.docker (Docker)
dotenv_local = BASE_DIR.parent / '.env.local'
dotenv_docker = BASE_DIR.parent / '.env.docker'

# In Docker (DOCKER_ENV set), always use .env.docker
# Locally (no DOCKER_ENV), prefer .env.local if it exists
if os.environ.get('DOCKER_ENV'):
    if dotenv_docker.exists():
        load_dotenv(dotenv_path=dotenv_docker, override=True)
        db_root = os.getenv('DB_ROOT_PATH')
        if db_root:
            sys.stderr.write(f"✓ Loaded .env.docker: DB_ROOT_PATH={db_root}\n")
        else:
            sys.stderr.write("⚠ Warning: .env.docker loaded but DB_ROOT_PATH not found\n")
    else:
        sys.stderr.write(f"⚠ Warning: .env.docker not found at {dotenv_docker}\n")
else:
    # Local development - prefer .env.local
    if dotenv_local.exists():
        load_dotenv(dotenv_path=dotenv_local, override=True)
        sys.stderr.write("✓ Loaded .env.local for local development\n")
    elif dotenv_docker.exists():
        load_dotenv(dotenv_path=dotenv_docker, override=True)
        sys.stderr.write("✓ Loaded .env.docker (fallback for local development)\n")
    else:
        sys.stderr.write("⚠ Warning: No .env file found\n")

APPEND_SLASH = True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

# Logging configuration from environment
BACKEND_LOG_LEVEL = os.environ.get("BACKEND_LOGGING_LEVEL", "INFO").upper()

# Backend AI model selection (for LLM defaults)
BACKEND_AI_PROVIDER = os.environ.get("BACKEND_AI_PROVIDER", "").lower()
BACKEND_AI_MODEL = os.environ.get("BACKEND_AI_MODEL", "")

# Derive a LiteLLM-compatible model id for convenience in parts of the app
def _derive_litellm_model(provider: str, model: str) -> str:
    mapping = {
        'openai': '',
        'anthropic': 'claude/',
        'gemini': 'gemini/',
        'mistral': 'mistral/',
        'ollama': 'ollama/',
        'openrouter': 'openrouter/',
        'groq': 'groq/',
        # OpenAI-compatible providers keep raw model id by default
        'deepseek': '',
        'lm_studio': '',
    }
    prefix = mapping.get(provider, '')
    # For openrouter, preserve vendor prefix if present; otherwise accept as-is
    if provider == 'openrouter':
        return f"openrouter/{model}"
    if provider == 'groq':
        # If model already includes a vendor prefix (e.g., meta-llama/..), keep it
        return f"groq/{model.split('/',1)[1]}" if '/' in model and not model.startswith('groq/') else f"groq/{model}"
    return f"{prefix}{model}" if prefix else model

DEFAULT_LITELLM_MODEL = _derive_litellm_model(BACKEND_AI_PROVIDER, BACKEND_AI_MODEL) if BACKEND_AI_PROVIDER and BACKEND_AI_MODEL else None

ALLOWED_HOSTS = [
    "thoth-be",
    "thoth-be-proxy",
    "backend",
    "backend:8000",
    "thoth-sql-generator",
    "sql-generator",
    "localhost",
    "127.0.0.1",
]

# Add ALLOWED_HOSTS from environment variables
env_allowed_hosts = os.environ.get("ALLOWED_HOSTS", "").split(",")
for host in env_allowed_hosts:
    host = host.strip()
    if host and host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",  # Add CORS headers support
    "thoth_core",
    "thoth_ai_backend",
    "rest_framework",
    "rest_framework.authtoken",
    "crispy_forms",
    "crispy_bootstrap5",
    "allauth",
    "allauth.account",
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

# Verify that REST_FRAMEWORK is configured correctly
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        # Other authentication methods...
    ],
    # Other configurations...
}

if DEBUG:
    INSTALLED_APPS.append("django_browser_reload")

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Add CORS middleware first
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "thoth_core.middleware.TokenAuthenticationMiddleware",  # SSO Token authentication
    "thoth_core.middleware.SessionRefreshMiddleware",  # Keep sessions alive
    "thoth_core.middleware.WorkspaceMiddleware",  # Added Workspace Middleware
    "thoth_core.cache_middleware.NoCacheMiddleware",  # Added No-Cache Middleware
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

if DEBUG:
    MIDDLEWARE.append("django_browser_reload.middleware.BrowserReloadMiddleware")

ROOT_URLCONF = "Thoth.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "thoth_core.context_processors.workspace_context",  # Add workspace context
            ],
        },
    },
]

WSGI_APPLICATION = "Thoth.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Using dynamic database configuration based on environment variables
DATABASE_URL = os.environ.get("DATABASE_URL")
DB_ENGINE = os.environ.get("DB_ENGINE")
DB_NAME = os.environ.get("DB_NAME")
DB_USER = os.environ.get("DB_USER")
DB_PASSWORD = os.environ.get("DB_PASSWORD")
DB_HOST = os.environ.get("DB_HOST")
DB_PORT = os.environ.get("DB_PORT")

# Development/Production check for SQLite paths
DOCKER_ENV = os.environ.get("DOCKER_ENV", None)

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=60,
        )
    }
    
    # Add schema support for PostgreSQL
    if DATABASE_URL.strip().startswith(("postgres://", "postgresql://")):
        db_schema = os.environ.get("DB_SCHEMA", "thoth_schema")
        options = DATABASES["default"].get("OPTIONS", {})
        options["options"] = f"-c search_path={db_schema},public"
        DATABASES["default"]["OPTIONS"] = options

elif DB_ENGINE == "django.db.backends.postgresql" and DB_NAME and DB_USER and DB_PASSWORD and DB_HOST:
    # Explicit PostgreSQL configuration (Swarm / External DB)
    db_schema = os.environ.get("DB_SCHEMA", "thoth_schema")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": DB_NAME,
            "USER": DB_USER,
            "PASSWORD": DB_PASSWORD,
            "HOST": DB_HOST,
            "PORT": DB_PORT or "5432",
            "OPTIONS": {
                "options": f"-c search_path={db_schema},public",
            },
        }
    }
    print(f"✓ Configured external PostgreSQL: Host={DB_HOST}, DB={DB_NAME}, Schema={db_schema}")

else:
    # Fallback to SQLite (legacy behavior)
    if DOCKER_ENV:  # Running in Docker
        sqlite_db_name = os.environ.get("DB_NAME_DOCKER", "/app/backend_db/db.sqlite3")
    else:  # Running locally
        sqlite_db_name = BASE_DIR / os.environ.get("DB_NAME_LOCAL", "db.sqlite3")

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": sqlite_db_name,
        }
    }
    # print(f"✓ Configured SQLite: {sqlite_db_name}")

# Secrets directories for sensitive uploads (e.g., SSH private keys)
# In Docker, prefer the mounted secrets volume at /vol/secrets; locally, use project ./secrets
SECRETS_BASE_DIR = "/vol/secrets" if DOCKER_ENV else str(BASE_DIR / "secrets")
SSH_KEYS_DIR = os.path.join(SECRETS_BASE_DIR, "ssh_keys")
try:
    os.makedirs(SSH_KEYS_DIR, exist_ok=True)
    # Best-effort: restrict permissions to owner only
    try:
        os.chmod(SSH_KEYS_DIR, 0o700)
    except Exception:
        pass
except Exception:
    # Do not block startup if we cannot create the directory; admin will handle errors
    pass


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Rome"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# STATIC_ROOT: where collectstatic gathers all static files
# In Docker, use /vol/static (mounted volume); locally, use backend/staticfiles
STATIC_ROOT = "/vol/static/" if DOCKER_ENV else os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django Allauth settings
ACCOUNT_SESSION_REMEMBER = (
    None  # Show "remember me" checkbox but don't check it by default
)
SESSION_COOKIE_AGE = (
    60 * 60 * 24 * 30
)  # Session cookie expires after 30 days when "remember me" is checked

# Session cookie configuration for frontend/backend sharing
SESSION_COOKIE_NAME = 'thoth_sessionid'
SESSION_COOKIE_DOMAIN = None  # Will be set dynamically based on environment
SESSION_COOKIE_PATH = '/'
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = False  # Allow JavaScript access for frontend
SESSION_COOKIE_SAMESITE = 'Lax'  # Allow cross-origin requests from frontend
CSRF_COOKIE_NAME = 'thoth_csrftoken'
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": "DEBUG",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs", "thoth.log"),
            "formatter": "verbose",
            "when": "midnight",
            "interval": 1,
            "backupCount": 0,  # We'll handle cleanup with our custom command
            "encoding": "utf-8",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": BACKEND_LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "thoth_core": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "thoth_core.authentication": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "thoth_core.permissions": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        # Reduce plugin registration spam
        "thoth_dbmanager": {
            "handlers": ["file"],  # Only to file, not console
            "level": "WARNING",  # Reduce plugin registration messages
            "propagate": False,
        },
        "thoth_sqldb2": {
            "handlers": ["file"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

# Ensure logs directory exists
os.makedirs(os.path.join(BASE_DIR, "logs"), exist_ok=True)

# Cache configuration - using database cache for thread safety
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "thoth_cache_table",
    }
}

# Load API key from environment or secrets volume
API_KEY = os.environ.get("DJANGO_API_KEY")
if not API_KEY:
    try:
        # Try to load from secrets volume if in Docker
        api_key_file = "/vol/secrets/django_api_key"
        if os.path.exists(api_key_file):
            with open(api_key_file, "r") as f:
                API_KEY = f.read().strip()
    except Exception:
        pass  # If loading fails, API_KEY remains None

# CORS Configuration for Frontend Integration
# Allow requests from Next.js frontend (localhost:3200 for local dev, localhost:3040 for Docker)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3200",  # Local development frontend
    "http://127.0.0.1:3200",  # Local development frontend
    "http://localhost:3040",  # Docker frontend port
    "http://127.0.0.1:3040",  # Docker frontend port
    "http://localhost:8040",  # Backend Docker port (via proxy)
    "http://127.0.0.1:8040",  # Backend Docker port (via proxy)
    "http://localhost:80",    # Web proxy port
    "http://127.0.0.1:80",    # Web proxy port
    "http://localhost:7001",  # Docker Swarm Frontend
    "http://127.0.0.1:7001",  # Docker Swarm Frontend
    "http://localhost:7010",  # Docker Swarm Proxy
    "http://127.0.0.1:7010",  # Docker Swarm Proxy
]

# Add CORS_ALLOWED_ORIGINS from environment variables (for remote deployments)
# Format: comma-separated list of origins, e.g., "http://server.com:3040,http://server.com:8040"
env_cors_origins = os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")
for origin in env_cors_origins:
    origin = origin.strip()
    if origin and origin not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(origin)

# For development, allow all origins from localhost
if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://localhost:\d+$",
        r"^http://127\.0\.0\.1:\d+$",
    ]

# Allow credentials for authentication
CORS_ALLOW_CREDENTIALS = True

# Allow specific headers
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-api-key",  # For API key authentication
]

# Allow specific methods
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
