# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Django settings for Thoth project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment variables are now loaded from root .env.local or .env.docker
# No need to load local env files as they are managed centrally
# load_dotenv(BASE_DIR / '.env')  # Deprecated - use root .env.local
# load_dotenv(BASE_DIR / '_env')  # Deprecated - use root .env.docker

APPEND_SLASH = False

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"
ALLOWED_HOSTS = [
    "thoth-be",
    "thoth-be-proxy",
    "backend",
    "backend:8000",
    "thoth-sql-generator",
    "sql-generator",
    "localhost",
    "127.0.0.1",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",  # Add CORS headers support
    "thoth_core",
    "thoth_ai_backend",
    "rest_framework",
    "rest_framework.authtoken",
    "crispy_forms",
    "crispy_bootstrap5",
    "allauth",
    "allauth.account",
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

# Verify that REST_FRAMEWORK is configured correctly
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        # Other authentication methods...
    ],
    # Other configurations...
}

if DEBUG:
    INSTALLED_APPS.append("django_browser_reload")

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Add CORS middleware first
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "thoth_core.middleware.WorkspaceMiddleware",  # Added Workspace Middleware
    "thoth_core.cache_middleware.NoCacheMiddleware",  # Added No-Cache Middleware
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

if DEBUG:
    MIDDLEWARE.append("django_browser_reload.middleware.BrowserReloadMiddleware")

ROOT_URLCONF = "Thoth.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "thoth_core.context_processors.workspace_context",  # Add workspace context
            ],
        },
    },
]

WSGI_APPLICATION = "Thoth.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

IS_DOCKER = os.environ.get("IS_DOCKER", "False") == "True"
if IS_DOCKER:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.environ.get("DB_NAME_DOCKER", "/app/data/db.sqlite3"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / os.environ.get("DB_NAME_LOCAL", "db.sqlite3"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Rome"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = "/vol/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django Allauth settings
ACCOUNT_SESSION_REMEMBER = (
    None  # Show "remember me" checkbox but don't check it by default
)
SESSION_COOKIE_AGE = (
    60 * 60 * 24 * 30
)  # Session cookie expires after 30 days when "remember me" is checked

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": "DEBUG",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs", "thoth.log"),
            "formatter": "verbose",
            "when": "midnight",
            "interval": 1,
            "backupCount": 0,  # We'll handle cleanup with our custom command
            "encoding": "utf-8",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "thoth_core": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "thoth_core.authentication": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "thoth_core.permissions": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        # Reduce plugin registration spam
        "thoth_dbmanager": {
            "handlers": ["file"],  # Only to file, not console
            "level": "WARNING",  # Reduce plugin registration messages
            "propagate": False,
        },
        "thoth_sqldb2": {
            "handlers": ["file"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

# Ensure logs directory exists
os.makedirs(os.path.join(BASE_DIR, "logs"), exist_ok=True)

# Cache configuration - using database cache for thread safety
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "thoth_cache_table",
    }
}

# Load API key from environment or secrets volume
API_KEY = os.environ.get("DJANGO_API_KEY")
if not API_KEY:
    try:
        # Try to load from secrets volume if in Docker
        api_key_file = "/vol/secrets/django_api_key"
        if os.path.exists(api_key_file):
            with open(api_key_file, "r") as f:
                API_KEY = f.read().strip()
    except Exception:
        pass  # If loading fails, API_KEY remains None

# CORS Configuration for Frontend Integration
# Allow requests from Next.js frontend (localhost:3200 for local dev, localhost:3040 for Docker)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3200",  # Local development frontend
    "http://127.0.0.1:3200",  # Local development frontend
    "http://localhost:3040",  # Docker frontend port
    "http://127.0.0.1:3040",  # Docker frontend port
    "http://localhost:8040",  # Backend Docker port (via proxy)
    "http://127.0.0.1:8040",  # Backend Docker port (via proxy)
    "http://localhost:80",    # Web proxy port
    "http://127.0.0.1:80",    # Web proxy port
]

# For development, allow all origins from localhost
if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://localhost:\d+$",
        r"^http://127\.0\.0\.1:\d+$",
    ]

# Allow credentials for authentication
CORS_ALLOW_CREDENTIALS = True

# Allow specific headers
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-api-key",  # For API key authentication
]

# Allow specific methods
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
