-- MariaDB schema for california_schools database
CREATE DATABASE IF NOT EXISTS california_schools;
USE california_schools;

CREATE TABLE frpm (
CDSCode TEXT PRIMARY KEY NOT NULL COMMENT 'CDSCode',
Academic Year TEXT  COMMENT 'Academic Year',
County Code TEXT  COMMENT 'County Code',
District Code INT  COMMENT 'District Code',
School Code TEXT  COMMENT 'School Code',
County Name TEXT  COMMENT 'County Code',
District Name TEXT  COMMENT 'District Name',
School Name TEXT  COMMENT 'School Name',
District Type TEXT  COMMENT 'District Type',
School Type TEXT  COMMENT 'School Type',
Educational Option Type TEXT  COMMENT 'Educational Option Type',
NSLP Provision Status TEXT  COMMENT 'NSLP Provision Status',
Charter School (Y/N) INT  COMMENT 'Charter School (Y/N)',
Charter School Number TEXT  COMMENT 'Charter School Number',
Charter Funding Type TEXT  COMMENT 'Charter Funding Type',
IRC INT,
Low Grade TEXT  COMMENT 'Low Grade',
High Grade TEXT  COMMENT 'High Grade',
Enrollment (K-12) DECIMAL(10,2)  COMMENT 'Enrollment (K-12)',
Free Meal Count (K-12) DECIMAL(10,2)  COMMENT 'Free Meal Count (K-12)',
Percent (%) Eligible Free (K-12) DECIMAL(10,2),
FRPM Count (K-12) DECIMAL(10,2)  COMMENT 'Free or Reduced Price Meal Count (K-12)',
Percent (%) Eligible FRPM (K-12) DECIMAL(10,2),
Enrollment (Ages 5-17) DECIMAL(10,2)  COMMENT 'Enrollment (Ages 5-17)',
Free Meal Count (Ages 5-17) DECIMAL(10,2)  COMMENT 'Free Meal Count (Ages 5-17)',
Percent (%) Eligible Free (Ages 5-17) DECIMAL(10,2),
FRPM Count (Ages 5-17) DECIMAL(10,2),
Percent (%) Eligible FRPM (Ages 5-17) DECIMAL(10,2),
2013-14 CALPADS Fall 1 Certification Status INT  COMMENT '2013-14 CALPADS Fall 1 Certification Status'
);

CREATE TABLE satscores (
cds TEXT PRIMARY KEY NOT NULL COMMENT 'California Department Schools',
rtype TEXT NOT NULL COMMENT 'rtype',
sname TEXT  COMMENT 'school name',
dname TEXT  COMMENT 'district segment',
cname TEXT  COMMENT 'county name',
enroll12 INT NOT NULL COMMENT 'enrollment (1st-12nd grade)',
NumTstTakr INT NOT NULL COMMENT 'Number of Test Takers in this school',
AvgScrRead INT  COMMENT 'average scores in Reading',
AvgScrMath INT  COMMENT 'average scores in Math',
AvgScrWrite INT  COMMENT 'average scores in writing',
NumGE1500 INT  COMMENT 'Number of Test Takers Whose Total SAT Scores Are Greater or Equal to 1500'
);

CREATE TABLE schools (
CDSCode TEXT PRIMARY KEY NOT NULL COMMENT 'CDSCode',
NCESDist TEXT  COMMENT 'This field represents the 7-digit National Center for Educational Statistics (NCES) school district identification number. The first 2 digits identify the state and the last 5 digits identify the school district. Combined, they make a unique 7-digit ID for each school district.',
NCESSchool TEXT  COMMENT 'This field represents the 5-digit NCES school identification number. The NCESSchool combined with the NCESDist form a unique 12-digit ID for each school.',
StatusType TEXT NOT NULL COMMENT 'This field identifies the status of the district.',
County TEXT NOT NULL COMMENT 'County name',
District TEXT NOT NULL COMMENT 'District',
School TEXT  COMMENT 'School',
Street TEXT  COMMENT 'Street',
StreetAbr TEXT  COMMENT 'The abbreviated street address of the school, district, or administrative authority’s physical location.',
City TEXT  COMMENT 'City',
Zip TEXT  COMMENT 'Zip',
State TEXT  COMMENT 'State',
MailStreet TEXT  COMMENT 'MailStreet',
MailStrAbr TEXT,
MailCity TEXT,
MailZip TEXT,
MailState TEXT,
Phone TEXT  COMMENT 'Phone',
Ext TEXT  COMMENT 'The phone number extension of the school, district, or administrative authority.',
Website TEXT  COMMENT 'The website address of the school, district, or administrative authority.',
OpenDate DATE  COMMENT 'The date the school opened.',
ClosedDate DATE  COMMENT 'The date the school closed.',
Charter INT  COMMENT 'This field identifies a charter school.',
CharterNum TEXT  COMMENT 'The charter school number,',
FundingType TEXT  COMMENT 'Indicates the charter school funding type',
DOC TEXT NOT NULL COMMENT 'District Ownership Code',
DOCType TEXT NOT NULL COMMENT 'The District Ownership Code Type is the text description of the DOC category.',
SOC TEXT  COMMENT 'The School Ownership Code is a numeric code used to identify the type of school.',
SOCType TEXT  COMMENT 'The School Ownership Code Type is the text description of the type of school.',
EdOpsCode TEXT  COMMENT 'The Education Option Code is a short text description of the type of education offered.',
EdOpsName TEXT  COMMENT 'Educational Option Name',
EILCode TEXT  COMMENT 'The Educational Instruction Level Code is a short text description of the institution''s type relative to the grade range served.',
EILName TEXT  COMMENT 'The Educational Instruction Level Name is the long text description of the institution’s type relative to the grade range served.',
GSoffered TEXT  COMMENT 'The grade span offered is the lowest grade and the highest grade offered or supported by the school, district, or administrative authority. This field might differ from the grade span served as reported in the most recent certified California Longitudinal Pupil Achievement (CALPADS) Fall 1 data collection.',
GSserved TEXT  COMMENT 'It is the lowest grade and the highest grade of student enrollment as reported in the most recent certified CALPADS Fall 1 data collection. Only K–12 enrollment is reported through CALPADS. This field may differ from the grade span offered.',
Virtual TEXT  COMMENT 'This field identifies the type of virtual instruction offered by the school. Virtual instruction is instruction in which students and teachers are separated by time and/or location, and interaction occurs via computers and/or telecommunications technologies.',
Magnet INT  COMMENT 'This field identifies whether a school is a magnet school and/or provides a magnet program.',
Latitude DECIMAL(10,2)  COMMENT 'The angular distance (expressed in degrees) between the location of the school, district, or administrative authority and the equator measured north to south.',
Longitude DECIMAL(10,2)  COMMENT 'The angular distance (expressed in degrees) between the location of the school, district, or administrative authority and the prime meridian (Greenwich, England) measured from west to east.',
AdmFName1 TEXT  COMMENT 'administrator''s first name',
AdmLName1 TEXT  COMMENT 'administrator''s last name',
AdmEmail1 TEXT  COMMENT 'administrator''s email address',
AdmFName2 TEXT,
AdmLName2 TEXT,
AdmEmail2 TEXT,
AdmFName3 TEXT,
AdmLName3 TEXT,
AdmEmail3 TEXT,
LastUpdate DATE NOT NULL
);

