-- MariaDB schema for european_football_2 database
CREATE DATABASE IF NOT EXISTS european_football_2;
USE european_football_2;

CREATE TABLE Player_Attributes (
id INT PRIMARY KEY  COMMENT 'the unique id for players',
player_fifa_api_id INT  COMMENT 'the id of the player fifa api',
player_api_id INT  COMMENT 'the id of the player api',
date TEXT  COMMENT 'date',
overall_rating INT  COMMENT 'the overall rating of the player',
potential INT  COMMENT 'potential of the player',
preferred_foot TEXT  COMMENT 'the player''s preferred foot when attacking',
attacking_work_rate TEXT  COMMENT 'the player''s attacking work rate',
defensive_work_rate TEXT  COMMENT 'the player''s defensive work rate',
crossing INT  COMMENT 'the player''s crossing score',
finishing INT  COMMENT 'the player''s finishing rate',
heading_accuracy INT  COMMENT 'the player''s heading accuracy',
short_passing INT  COMMENT 'the player''s short passing score',
volleys INT  COMMENT 'the player''s volley score',
dribbling INT  COMMENT 'the player''s dribbling score',
curve INT  COMMENT 'the player''s curve score',
free_kick_accuracy INT  COMMENT 'the player''s free kick accuracy',
long_passing INT  COMMENT 'the player''s long passing score',
ball_control INT  COMMENT 'the player''s ball control score',
acceleration INT  COMMENT 'the player''s acceleration score',
sprint_speed INT  COMMENT 'the player''s sprint speed',
agility INT  COMMENT 'the player''s agility',
reactions INT  COMMENT 'the player''s reactions score',
balance INT  COMMENT 'the player''s balance score',
shot_power INT  COMMENT 'the player''s shot power',
jumping INT  COMMENT 'the player''s jumping score',
stamina INT  COMMENT 'the player''s stamina score',
strength INT  COMMENT 'the player''s strength score',
long_shots INT  COMMENT 'the player''s long shots score',
aggression INT  COMMENT 'the player''s aggression score',
interceptions INT  COMMENT 'the player''s interceptions score',
positioning INT  COMMENT 'the player''s 
positioning score',
vision INT  COMMENT 'the player''s vision score',
penalties INT  COMMENT 'the player''s penalties score',
marking INT  COMMENT 'the player''s markingscore',
standing_tackle INT  COMMENT 'the player''s standing tackle score',
sliding_tackle INT  COMMENT 'the player''s sliding tackle score',
gk_diving INT  COMMENT 'the player''s goalkeep diving score',
gk_handling INT  COMMENT 'the player''s goalkeep diving score',
gk_kicking INT  COMMENT 'the player''s goalkeep kicking score',
gk_positioning INT  COMMENT 'the player''s goalkeep positioning score',
gk_reflexes INT  COMMENT 'the player''s goalkeep reflexes score'
);

CREATE TABLE Player (
id INT PRIMARY KEY  COMMENT 'the unique id for players',
player_api_id INT  COMMENT 'the id of the player api',
player_name TEXT  COMMENT 'player name',
player_fifa_api_id INT  COMMENT 'the id of the player fifa api',
birthday TEXT  COMMENT 'the player''s birthday',
height INT  COMMENT 'the player''s height',
weight INT  COMMENT 'the player''s weight'
);

CREATE TABLE League (
id INT PRIMARY KEY  COMMENT 'the unique id for leagues',
country_id INT  COMMENT 'the unique id for countries',
name TEXT  COMMENT 'league name'
);

CREATE TABLE Country (
id INT PRIMARY KEY  COMMENT 'the unique id for countries',
name TEXT  COMMENT 'country name'
);

CREATE TABLE Team (
id INT PRIMARY KEY  COMMENT 'the unique id for teams',
team_api_id INT  COMMENT 'the id of the team api',
team_fifa_api_id INT  COMMENT 'the id of the team fifa api',
team_long_name TEXT  COMMENT 'the team''s long name',
team_short_name TEXT  COMMENT 'the team''s short name'
);

CREATE TABLE Team_Attributes (
id INT PRIMARY KEY  COMMENT 'the unique id for teams',
team_fifa_api_id INT  COMMENT 'the id of the team fifa api',
team_api_id INT  COMMENT 'the id of the team api',
date TEXT  COMMENT 'Date',
buildUpPlaySpeed INT  COMMENT 'the speed in which attacks are put together',
buildUpPlaySpeedClass TEXT  COMMENT 'the speed class',
buildUpPlayDribbling INT  COMMENT 'the tendency/ frequency of dribbling',
buildUpPlayDribblingClass TEXT  COMMENT 'the dribbling class',
buildUpPlayPassing INT  COMMENT 'affects passing distance and support from teammates',
buildUpPlayPassingClass TEXT  COMMENT 'the passing class',
buildUpPlayPositioningClass TEXT  COMMENT 'A team''s freedom of movement in the 1st two thirds of the pitch',
chanceCreationPassing INT  COMMENT 'Amount of risk in pass decision and run support',
chanceCreationPassingClass TEXT  COMMENT 'the chance creation passing class',
chanceCreationCrossing INT  COMMENT 'The tendency / frequency of crosses into the box',
chanceCreationCrossingClass TEXT  COMMENT 'the chance creation crossing class',
chanceCreationShooting INT  COMMENT 'The tendency / frequency of shots taken',
chanceCreationShootingClass TEXT  COMMENT 'the chance creation shooting class',
chanceCreationPositioningClass TEXT  COMMENT 'A teams freedom of movement in the final third of the pitch',
defencePressure INT  COMMENT 'Affects how high up the pitch the team will start pressuring',
defencePressureClass TEXT  COMMENT 'the defence pressure class',
defenceAggression INT  COMMENT 'Affect the teams approach to tackling the ball possessor',
defenceAggressionClass TEXT  COMMENT 'the defence aggression class',
defenceTeamWidth INT  COMMENT 'Affects how much the team will shift to the ball side',
defenceTeamWidthClass TEXT  COMMENT 'the defence team width class',
defenceDefenderLineClass TEXT  COMMENT 'Affects the shape and strategy of the defence'
);

CREATE TABLE Match (
id INT PRIMARY KEY  COMMENT 'the unique id for matches',
country_id INT  COMMENT 'country id',
league_id INT  COMMENT 'league id',
season TEXT  COMMENT 'the season of the match',
stage INT  COMMENT 'the stage of the match',
date TEXT  COMMENT 'the date of the match',
match_api_id INT  COMMENT 'the id of the match api',
home_team_api_id INT  COMMENT 'the id of the home team api',
away_team_api_id INT  COMMENT 'the id of the away team api',
home_team_goal INT  COMMENT 'the goal of the home team',
away_team_goal INT  COMMENT 'the goal of the away team',
home_player_X1 INT,
home_player_X2 INT,
home_player_X3 INT,
home_player_X4 INT,
home_player_X5 INT,
home_player_X6 INT,
home_player_X7 INT,
home_player_X8 INT,
home_player_X9 INT,
home_player_X10 INT,
home_player_X11 INT,
away_player_X1 INT,
away_player_X2 INT,
away_player_X3 INT,
away_player_X4 INT,
away_player_X5 INT,
away_player_X6 INT,
away_player_X7 INT,
away_player_X8 INT,
away_player_X9 INT,
away_player_X10 INT,
away_player_X11 INT,
home_player_Y1 INT,
home_player_Y2 INT,
home_player_Y3 INT,
home_player_Y4 INT,
home_player_Y5 INT,
home_player_Y6 INT,
home_player_Y7 INT,
home_player_Y8 INT,
home_player_Y9 INT,
home_player_Y10 INT,
home_player_Y11 INT,
away_player_Y1 INT,
away_player_Y2 INT,
away_player_Y3 INT,
away_player_Y4 INT,
away_player_Y5 INT,
away_player_Y6 INT,
away_player_Y7 INT,
away_player_Y8 INT,
away_player_Y9 INT,
away_player_Y10 INT,
away_player_Y11 INT,
home_player_1 INT,
home_player_2 INT,
home_player_3 INT,
home_player_4 INT,
home_player_5 INT,
home_player_6 INT,
home_player_7 INT,
home_player_8 INT,
home_player_9 INT,
home_player_10 INT,
home_player_11 INT,
away_player_1 INT,
away_player_2 INT,
away_player_3 INT,
away_player_4 INT,
away_player_5 INT,
away_player_6 INT,
away_player_7 INT,
away_player_8 INT,
away_player_9 INT,
away_player_10 INT,
away_player_11 INT,
goal TEXT  COMMENT 'the goal of the match',
shoton TEXT  COMMENT 'the shot on goal of the match',
shotoff TEXT  COMMENT 'the shot off goal of the match, which is the opposite of shot on',
foulcommit TEXT  COMMENT 'the fouls occurred in the match',
card TEXT  COMMENT 'the cards given in the match',
cross TEXT  COMMENT 'Balls sent into the opposition team''s area from a wide position in the match',
corner TEXT  COMMENT 'Ball goes out of play for a corner kick in the match',
possession TEXT  COMMENT 'The duration from a player taking over the ball in the match',
B365H DECIMAL(10,2),
B365D DECIMAL(10,2),
B365A DECIMAL(10,2),
BWH DECIMAL(10,2),
BWD DECIMAL(10,2),
BWA DECIMAL(10,2),
IWH DECIMAL(10,2),
IWD DECIMAL(10,2),
IWA DECIMAL(10,2),
LBH DECIMAL(10,2),
LBD DECIMAL(10,2),
LBA DECIMAL(10,2),
PSH DECIMAL(10,2),
PSD DECIMAL(10,2),
PSA DECIMAL(10,2),
WHH DECIMAL(10,2),
WHD DECIMAL(10,2),
WHA DECIMAL(10,2),
SJH DECIMAL(10,2),
SJD DECIMAL(10,2),
SJA DECIMAL(10,2),
VCH DECIMAL(10,2),
VCD DECIMAL(10,2),
VCA DECIMAL(10,2),
GBH DECIMAL(10,2),
GBD DECIMAL(10,2),
GBA DECIMAL(10,2),
BSH DECIMAL(10,2),
BSD DECIMAL(10,2),
BSA DECIMAL(10,2)
);

