#!/bin/bash
# Copyright (c) 2025 Marco Pancotti
# This file is part of ThothAI and is released under the Apache 2.0.
# See the LICENSE.md file in the project root for full license information.

set -e

# Wait for secrets to be available (generated by backend)
# This is needed because in Docker Swarm all services start simultaneously,
# but the backend takes time to generate secrets.
wait_for_secrets() {
    local secret_file="$1"
    local max_wait="${SECRETS_WAIT_TIMEOUT:-300}"  # 5 minutes default
    local interval=5
    local elapsed=0
    
    echo "Waiting for secrets to be available (max ${max_wait}s)..."
    
    while [ ! -f "$secret_file" ]; do
        if [ $elapsed -ge $max_wait ]; then
            echo "ERROR: Timeout waiting for secrets after ${elapsed}s"
            return 1
        fi
        echo "Secrets not ready yet, waiting... (${elapsed}s/${max_wait}s)"
        sleep $interval
        elapsed=$((elapsed + interval))
    done
    
    echo "Secrets are available after ${elapsed}s"
    return 0
}

# Wait for the django_api_key to exist
if ! wait_for_secrets "/vol/secrets/django_api_key"; then
    exit 1
fi

# Read Django API_KEY from shared secrets volume
export DJANGO_API_KEY=$(cat /vol/secrets/django_api_key)
echo "Django API_KEY loaded from secrets volume"
echo "API key loaded: ${DJANGO_API_KEY:0:10}..."

# Initialize shared data volume
if [ -f "/app/scripts/init-shared-data.sh" ]; then
    echo "Initializing shared data volume..."
    /app/scripts/init-shared-data.sh
fi

# Get the port from environment or use default
PORT=${PORT:-8001}

# Run the SQL Generator with environment variables
cd /app
# Activate the virtual environment created by uv and run the server
exec env DJANGO_API_KEY="$DJANGO_API_KEY" /app/.venv/bin/python run_server.py $PORT