#!/bin/sh
# Copyright (c) 2025 Marco Pancotti
# This file is part of ThothAI and is released under the Apache 2.0.
# See the LICENSE.md file in the project root for full license information.

set -e

# Wait for secrets to be available (generated by backend)
# This is needed because in Docker Swarm all services start simultaneously,
# but the backend takes time to generate secrets.
wait_for_secrets() {
    secret_file="$1"
    max_wait="${SECRETS_WAIT_TIMEOUT:-300}"  # 5 minutes default
    interval=5
    elapsed=0
    
    echo "Waiting for secrets to be available (max ${max_wait}s)..."
    
    while [ ! -f "$secret_file" ]; do
        if [ $elapsed -ge $max_wait ]; then
            echo "ERROR: Timeout waiting for secrets after ${elapsed}s"
            return 1
        fi
        echo "Secrets not ready yet, waiting... (${elapsed}s/${max_wait}s)"
        sleep $interval
        elapsed=$((elapsed + interval))
    done
    
    echo "Secrets are available after ${elapsed}s"
    return 0
}

# Wait for the django_api_key to exist
if ! wait_for_secrets "/vol/secrets/django_api_key"; then
    exit 1
fi

# Read Django API_KEY from shared secrets volume
export DJANGO_API_KEY=$(cat /vol/secrets/django_api_key)
echo "Django API_KEY loaded from secrets volume"
echo "API key loaded: ${DJANGO_API_KEY:0:10}..."

# Also export for Next.js runtime
export NEXT_PUBLIC_DJANGO_API_KEY="${DJANGO_API_KEY}"

# Run the Next.js application
exec npm run start