name: thoth-test-virtualdbs

services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: thoth-test-qdrant
    restart: unless-stopped
    ports:
      - "6334:6333"
      - "6335:6334"
    volumes:
      - qdrant_data:/qdrant/storage
      - ./qdrant/config:/qdrant/config
    networks:
      - thoth-test-virtualdbs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      start_period: 30s
      interval: 15s
      timeout: 10s
      retries: 3

  # Weaviate removed

  # Milvus Vector Database
  milvus-etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: thoth-test-milvus-etcd
    restart: unless-stopped
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - milvus_etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      - thoth-test-virtualdbs
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  milvus-minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: thoth-test-milvus-minio
    restart: unless-stopped
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - milvus_minio_data:/minio_data
    command: minio server /minio_data --console-address ":9001"
    networks:
      - thoth-test-virtualdbs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  milvus-standalone:
    image: milvusdb/milvus:latest
    container_name: thoth-test-milvus
    restart: unless-stopped
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: milvus-etcd:2379
      MINIO_ADDRESS: milvus-minio:9000
    volumes:
      - milvus_data:/var/lib/milvus
      - ./milvus/config:/milvus/configs
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - milvus-etcd
      - milvus-minio
    networks:
      - thoth-test-virtualdbs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      start_period: 90s
      interval: 30s
      timeout: 20s
      retries: 3

  # Milvus Attu Web UI
  milvus-attu:
    image: zilliz/attu:latest
    container_name: thoth-test-milvus-attu
    restart: unless-stopped
    environment:
      MILVUS_URL: milvus-standalone:19530
    ports:
      - "3002:3000"
    depends_on:
      - milvus-standalone
    networks:
      - thoth-test-virtualdbs

  # Chroma Vector Database
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: thoth-test-chroma
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
      - ./chroma/config:/chroma/config
    environment:
      IS_PERSISTENT: TRUE
      PERSIST_DIRECTORY: /chroma/chroma
      ANONYMIZED_TELEMETRY: FALSE
    networks:
      - thoth-test-virtualdbs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      start_period: 30s
      interval: 15s
      timeout: 10s
      retries: 3

  # PostgreSQL with pgvector extension
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: thoth-test-pgvector
    restart: unless-stopped
    environment:
      POSTGRES_USER: vector_user
      POSTGRES_PASSWORD: vector_password
      POSTGRES_DB: vector_db
    ports:
      - "5436:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./pgvector/init:/docker-entrypoint-initdb.d
    networks:
      - thoth-test-virtualdbs
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "vector_user", "-d", "vector_db"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  # pgAdmin for pgvector management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: thoth-test-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@thoth.local
      PGADMIN_DEFAULT_PASSWORD: admin_password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8082:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - pgvector
    networks:
      - thoth-test-virtualdbs

volumes:
  qdrant_data:
    driver: local
  
  milvus_etcd_data:
    driver: local
  milvus_minio_data:
    driver: local
  milvus_data:
    driver: local
  chroma_data:
    driver: local
  pgvector_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  thoth-test-virtualdbs:
    driver: bridge