# Generated by Django 5.2 on 2025-08-31 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='test_exec_agent',
        ),
        migrations.AddField(
            model_name='workspace',
            name='test_evaluator_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspaces_test_evaluator', to='thoth_core.agent'),
        ),
    ]
