# Generated by Django 5.2 on 2025-08-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_core', '0002_add_test_evaluator_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('EXTRACTKEYWORDS', 'Keywords Extractor'), ('SQLBASIC', 'SQL Generator - Basic'), ('SQLADVANCED', 'SQL Generator - Advanced'), ('SQLEXPERT', 'SQL Generator - Expert'), ('TESTGENERATORBASIC', 'Test Generator - Basic'), ('TESTGENERATORADVANCED', 'Test Generator - Advanced'), ('TESTGENERATOREXPERT', 'Test Generator - Expert'), ('TESTEVALUATOR', 'Test Evaluator'), ('EXPLAINSQL', 'SQL Explainer'), ('ASKFORHUMANHELP', 'Human Help Requester'), ('VALIDATEQUESTION', 'Question Validator')], default='EXTRACTKEYWORDS', max_length=255),
        ),
    ]
