# Generated by Django 5.2 on 2025-08-31 12:47

from django.db import migrations


def migrate_test_executor_to_evaluator(apps, schema_editor):
    """Migrate all TESTEXECUTOR agents to TESTEVALUATOR"""
    Agent = apps.get_model('thoth_core', 'Agent')
    Agent.objects.filter(agent_type='TESTEXECUTOR').update(agent_type='TESTEVALUATOR')


def reverse_migrate_evaluator_to_executor(apps, schema_editor):
    """Reverse migration: TESTEVALUATOR back to TESTEXECUTOR"""
    Agent = apps.get_model('thoth_core', 'Agent')
    Agent.objects.filter(agent_type='TESTEVALUATOR').update(agent_type='TESTEXECUTOR')


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_core', '0003_update_agent_choices_replace_executor_with_evaluator'),
    ]

    operations = [
        migrations.RunPython(
            migrate_test_executor_to_evaluator,
            reverse_migrate_evaluator_to_executor
        ),
    ]
