# Generated by Django 5.2 on 2025-09-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_core', '0007_thothlog_enhanced_evaluation_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thothlog',
            name='evaluation_case',
            field=models.CharField(blank=True, default='', help_text='Evaluation case category', max_length=100),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='evaluation_details',
            field=models.JSONField(blank=True, default=list, help_text='Detailed evaluation results as JSON array', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='evaluation_duration_ms',
            field=models.IntegerField(default=0, help_text='Evaluation duration in milliseconds'),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='evaluation_end',
            field=models.DateTimeField(blank=True, help_text='When evaluation ended', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='evaluation_start',
            field=models.DateTimeField(blank=True, help_text='When evaluation started', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='generated_tests_count',
            field=models.IntegerField(default=0, help_text='Number of tests generated'),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='pass_rates',
            field=models.JSONField(blank=True, default=dict, help_text='Pass rate statistics as JSON object', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='selected_sql_complexity',
            field=models.CharField(blank=True, help_text='Complexity level of the selected SQL query', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='sql_selection_duration_ms',
            field=models.IntegerField(default=0, help_text='SQL selection duration in milliseconds'),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='sql_selection_end',
            field=models.DateTimeField(blank=True, help_text='When SQL selection ended', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='sql_selection_start',
            field=models.DateTimeField(blank=True, help_text='When SQL selection started', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='sql_status',
            field=models.CharField(blank=True, default='', help_text='SQL execution status (e.g., passed, failed, error)', max_length=50),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='test_generation_duration_ms',
            field=models.IntegerField(default=0, help_text='Test generation duration in milliseconds'),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='test_generation_end',
            field=models.DateTimeField(blank=True, help_text='When test generation ended', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='test_generation_start',
            field=models.DateTimeField(blank=True, help_text='When test generation started', null=True),
        ),
        migrations.AlterField(
            model_name='basicaimodel',
            name='provider',
            field=models.CharField(choices=[('OPENAI', 'OpenAI'), ('ANTHROPIC', 'Anthropic'), ('CODESTRAL', 'Codestral'), ('DEEPSEEK', 'DeepSeek'), ('META', 'LLama'), ('LMSTUDIO', 'LM Studio'), ('MISTRAL', 'Mistral'), ('OLLAMA', 'Ollama'), ('OPENROUTER', 'OpenRouter'), ('GEMINI', 'Gemini'), ('GROQ', 'Groq')], default='ANTHROPIC', max_length=100),
        ),
        migrations.AlterField(
            model_name='thothlog',
            name='enhanced_evaluation_selected_sql',
            field=models.TextField(blank=True, default='', help_text='SQL query selected by enhanced evaluation process', null=True),
        ),
    ]
