# Generated by Django 5.2 on 2025-09-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_core', '0008_add_thothlog_execution_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='thothlog',
            name='sql_generation_duration_ms',
            field=models.IntegerField(default=0, help_text='SQL generation duration in milliseconds'),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='sql_generation_end',
            field=models.DateTimeField(blank=True, help_text='When SQL generation ended', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='sql_generation_start',
            field=models.DateTimeField(blank=True, help_text='When SQL generation started', null=True),
        ),
    ]
