# Generated by Django 5.2 on 2025-09-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_core', '0009_add_sql_generation_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thothlog',
            name='available_context_tokens',
        ),
        migrations.RemoveField(
            model_name='thothlog',
            name='full_schema_tokens_count',
        ),
        migrations.RemoveField(
            model_name='thothlog',
            name='schema_link_strategy',
        ),
        migrations.AddField(
            model_name='thothlog',
            name='context_retrieval_duration_ms',
            field=models.IntegerField(default=0, help_text='Context retrieval duration in milliseconds'),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='context_retrieval_end',
            field=models.DateTimeField(blank=True, help_text='When context retrieval ended', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='context_retrieval_start',
            field=models.DateTimeField(blank=True, help_text='When context retrieval (evidence + SQL examples) started', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='evaluation_judgments',
            field=models.JSONField(blank=True, help_text='Test-by-test judgments for each SQL candidate', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='flags_activated',
            field=models.JSONField(blank=True, help_text='Configuration flags from UI sidebar', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='gold_sql_extracted',
            field=models.TextField(blank=True, default='', help_text='Gold SQL examples extracted from vector database'),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='keyword_generation_duration_ms',
            field=models.IntegerField(default=0, help_text='Keyword generation duration in milliseconds'),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='keyword_generation_end',
            field=models.DateTimeField(blank=True, help_text='When keyword generation ended', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='keyword_generation_start',
            field=models.DateTimeField(blank=True, help_text='When keyword generation started', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='lsh_similar_columns',
            field=models.TextField(blank=True, default='', help_text='Similar columns found via LSH search'),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='process_end_time',
            field=models.DateTimeField(blank=True, help_text='Final timestamp when the entire process completed', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='reduced_tests',
            field=models.TextField(blank=True, default='', help_text='Reduced/filtered test list if test reduction was performed'),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='schema_preparation_duration_ms',
            field=models.IntegerField(default=0, help_text='Schema preparation duration in milliseconds'),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='schema_preparation_end',
            field=models.DateTimeField(blank=True, help_text='When schema preparation ended', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='schema_preparation_start',
            field=models.DateTimeField(blank=True, help_text='When schema preparation (LSH + Vector) started', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='test_reduction_duration_ms',
            field=models.IntegerField(default=0, help_text='Test reduction duration in milliseconds'),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='test_reduction_end',
            field=models.DateTimeField(blank=True, help_text='When test reduction ended', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='test_reduction_start',
            field=models.DateTimeField(blank=True, help_text='When test reduction started (if performed)', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='validation_duration_ms',
            field=models.IntegerField(default=0, help_text='Question validation duration in milliseconds'),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='validation_end',
            field=models.DateTimeField(blank=True, help_text='When question validation ended', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='validation_start',
            field=models.DateTimeField(blank=True, help_text='When question validation started', null=True),
        ),
    ]
