# Generated by Django 5.2 on 2025-09-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_core', '0010_logging_reorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='thothlog',
            name='belt_and_suspenders_duration_ms',
            field=models.IntegerField(default=0, help_text='Belt and suspenders evaluation duration in milliseconds'),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='belt_and_suspenders_end',
            field=models.DateTimeField(blank=True, help_text='When belt and suspenders enhanced evaluation ended', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='belt_and_suspenders_start',
            field=models.DateTimeField(blank=True, help_text='When belt and suspenders enhanced evaluation started', null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='belt_and_suspenders',
            field=models.BooleanField(default=False, help_text='Enable enhanced SQL selection for borderline evaluation cases using SqlEvaluator agent.', verbose_name='Belt and Suspenders'),
        ),
    ]
