# Generated by Django 5.2 on 2025-09-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_core', '0011_thothlog_belt_and_suspenders_duration_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thothlog',
            name='advanced_escalation',
            field=models.BooleanField(default=False, help_text='Flag indicating if escalation to ADVANCED level occurred'),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='expert_escalation',
            field=models.BooleanField(default=False, help_text='Flag indicating if escalation to EXPERT level occurred'),
        ),
    ]
