# Generated by Django 5.2 on 2025-09-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_core', '0014_alter_setting_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqldb',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('fr', 'French'), ('de', 'German'), ('nl', 'Dutch'), ('da', 'Danish'), ('sv', 'Swedish'), ('no', 'Norwegian'), ('is', 'Icelandic'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('cy', 'Welsh'), ('pl', 'Polish'), ('cs', 'Czech'), ('sk', 'Slovak'), ('sl', 'Slovene'), ('hu', 'Hungarian'), ('ro', 'Romanian'), ('bg', 'Bulgarian'), ('hr', 'Croatian'), ('sr', 'Serbian'), ('bs', 'Bosnian'), ('mk', 'Macedonian'), ('sq', 'Albanian'), ('uk', 'Ukrainian'), ('be', 'Belarusian'), ('ru', 'Russian'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('et', 'Estonian'), ('el', 'Greek'), ('tr', 'Turkish'), ('fi', 'Finnish'), ('mt', 'Maltese'), ('lb', 'Luxembourgish'), ('ca', 'Catalan'), ('eu', 'Basque'), ('gl', 'Galician'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean')], default='en', help_text='Default language for DB comments/prompts (ISO 639-1)', max_length=8),
        ),
        migrations.AlterField(
            model_name='thothlog',
            name='db_language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('fr', 'French'), ('de', 'German'), ('nl', 'Dutch'), ('da', 'Danish'), ('sv', 'Swedish'), ('no', 'Norwegian'), ('is', 'Icelandic'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('cy', 'Welsh'), ('pl', 'Polish'), ('cs', 'Czech'), ('sk', 'Slovak'), ('sl', 'Slovene'), ('hu', 'Hungarian'), ('ro', 'Romanian'), ('bg', 'Bulgarian'), ('hr', 'Croatian'), ('sr', 'Serbian'), ('bs', 'Bosnian'), ('mk', 'Macedonian'), ('sq', 'Albanian'), ('uk', 'Ukrainian'), ('be', 'Belarusian'), ('ru', 'Russian'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('et', 'Estonian'), ('el', 'Greek'), ('tr', 'Turkish'), ('fi', 'Finnish'), ('mt', 'Maltese'), ('lb', 'Luxembourgish'), ('ca', 'Catalan'), ('eu', 'Basque'), ('gl', 'Galician'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean')], max_length=8),
        ),
        migrations.AlterField(
            model_name='thothlog',
            name='question_language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('fr', 'French'), ('de', 'German'), ('nl', 'Dutch'), ('da', 'Danish'), ('sv', 'Swedish'), ('no', 'Norwegian'), ('is', 'Icelandic'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('cy', 'Welsh'), ('pl', 'Polish'), ('cs', 'Czech'), ('sk', 'Slovak'), ('sl', 'Slovene'), ('hu', 'Hungarian'), ('ro', 'Romanian'), ('bg', 'Bulgarian'), ('hr', 'Croatian'), ('sr', 'Serbian'), ('bs', 'Bosnian'), ('mk', 'Macedonian'), ('sq', 'Albanian'), ('uk', 'Ukrainian'), ('be', 'Belarusian'), ('ru', 'Russian'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('et', 'Estonian'), ('el', 'Greek'), ('tr', 'Turkish'), ('fi', 'Finnish'), ('mt', 'Maltese'), ('lb', 'Luxembourgish'), ('ca', 'Catalan'), ('eu', 'Basque'), ('gl', 'Galician'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean')], max_length=8),
        ),
    ]
