# Generated by Django 5.2 on 2025-09-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_core', '0016_add_sqldb_comment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='comment_model',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='example_rows_for_comment',
        ),
    ]
