# Generated by Django 5.2 on 2025-09-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_core', '0018_remove_setting_theme_language_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqldb',
            name='db_elements_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='db_elements_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='db_elements_status',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IDLE', max_length=20),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='db_elements_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
