# Generated by Django 5.2 on 2025-09-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_core', '0019_sqldb_db_elements_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thothlog',
            name='evidence_relevance_events',
            field=models.JSONField(blank=True, default=list, help_text='Detailed relevance guard diagnostics for evidence-derived tests', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='evidence_relevance_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Aggregated summary of evidence relevance evaluation', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='model_retry_events',
            field=models.JSONField(blank=True, default=list, help_text='Captured ModelRetry events with structured context', null=True),
        ),
        migrations.AddField(
            model_name='thothlog',
            name='retry_history',
            field=models.JSONField(blank=True, default=list, help_text='Compact retry history strings for SQL generation attempts', null=True),
        ),
    ]
