# Generated by Django 5.2 on 2025-10-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_core', '0020_thothlog_evidence_relevance_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqldb',
            name='ssh_allow_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='ssh_auth_method',
            field=models.CharField(choices=[('password', 'Password'), ('private_key', 'Private key'), ('password_and_key', 'Password + private key')], default='password', max_length=32),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='ssh_compression',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='ssh_connect_timeout',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='ssh_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='ssh_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='ssh_keepalive_interval',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='ssh_known_hosts_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='ssh_local_bind_host',
            field=models.CharField(blank=True, default='127.0.0.1', max_length=255),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='ssh_local_bind_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='ssh_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='ssh_port',
            field=models.IntegerField(blank=True, default=22, null=True),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='ssh_private_key_passphrase',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='ssh_private_key_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='ssh_strict_host_key_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='ssh_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
