# Generated by Django 5.2 on 2025-10-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_core', '0021_sqldb_ssh_allow_agent_sqldb_ssh_auth_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqldb',
            name='informix_dir',
            field=models.CharField(blank=True, default='/u/appl/ids10', help_text='Path to INFORMIXDIR on remote server (Informix SSH only)', max_length=500),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='informix_protocol',
            field=models.CharField(blank=True, default='onsoctcp', help_text='Informix connection protocol (default: onsoctcp)', max_length=50),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='informix_server',
            field=models.CharField(blank=True, help_text="INFORMIXSERVER name (required for Informix, e.g., 'ns1i10')", max_length=255),
        ),
        migrations.AlterField(
            model_name='sqldb',
            name='db_type',
            field=models.CharField(choices=[('Informix', 'Informix'), ('MariaDB', 'MariaDB'), ('MySQL', 'MySQL'), ('Oracle', 'Oracle'), ('PostgreSQL', 'PostgreSQL'), ('SQLServer', 'SQLServer'), ('SQLite', 'SQLite')], default='PostgreSQL', max_length=255),
        ),
    ]
