# Generated by Django 5.2 on 2025-11-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_core', '0022_add_informix_support'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.AlterModelOptions(
            name='aimodel',
            options={'verbose_name': 'AI Model', 'verbose_name_plural': 'AI Models'},
        ),
        migrations.AlterModelOptions(
            name='basicaimodel',
            options={'verbose_name': 'Basic AI Model', 'verbose_name_plural': 'Basic AI Models'},
        ),
        migrations.AlterModelOptions(
            name='relationship',
            options={'verbose_name': 'Relationship', 'verbose_name_plural': 'Relationships'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterModelOptions(
            name='sqlcolumn',
            options={'verbose_name': 'SQL Column', 'verbose_name_plural': 'SQL Columns'},
        ),
        migrations.AlterModelOptions(
            name='sqldb',
            options={'verbose_name': 'SQL Database', 'verbose_name_plural': 'SQL Databases'},
        ),
        migrations.AlterModelOptions(
            name='sqltable',
            options={'verbose_name': 'SQL Table', 'verbose_name_plural': 'SQL Tables'},
        ),
        migrations.AlterModelOptions(
            name='thothlog',
            options={'ordering': ['-started_at'], 'verbose_name': 'Thoth Log', 'verbose_name_plural': 'Thoth Logs'},
        ),
        migrations.AlterModelOptions(
            name='vectordb',
            options={'verbose_name': 'Vector Database', 'verbose_name_plural': 'Vector Databases'},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'verbose_name': 'Workspace', 'verbose_name_plural': 'Workspaces'},
        ),
    ]
