# Generated by Django 5.2 on 2026-04-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_core', '0025_add_async_status_fields_and_completed_with_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqldb',
            name='documentation_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='erd_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='gdpr_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sqldb',
            name='scope_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
